### ISSUE TITLE
Playground+SSL+subscriptions...

### ISSUE THREAD

**Issue by bitmodeler** [graphql-python/graphql-ws#37]
* GraphQL AioWS version: 0.3.0
* Python version: 3.7.1
* Operating System: Debian 10

queries using SSL from the GraphQL playground work; subscriptions do not.

I added an ssl_context to web.run_app; queries worked fine from the Playground client.

But when I tried a subscription (and it worked without SSL!):

**Playground:** `"error": "Could not connect to websocket endpoint ws://myhostnamealias.com:9000/subscriptions. Please check if the endpoint url is correct."`

**Server:** ```
SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f03ce8cbe48>
transport: <_SelectorSocketTransport closing fd=8 read=idle write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:1056)```

Now one curious thing I noticed: I was using certs for a specific host, and was using that same host in my URL in the GraphQL playground; but the playground error was using an alias host for the box. Is that coming from GraphQL Playground doing a reverse IP lookup? Or was aiohttp or graphql-ws doing a reverse name lookup somewhere because I used the aiohttp default host of "0.0.0.0"??

To rule that out, I reran the server with certificates for the other host name GraphQL had somewhere got and thought was the "right" one to use, and on aiohttp's web.run_app I used a "host" argument with the fully qualified host name the playground seemed to think was the "correct" one. Same result: queries worked; a subscription query reissued the same "Could not connect to websocket endpoint..." error. Removed the SSL from aiohttp and used "http:" in my queries+subscriptions -all worked.

Are there perhaps extra config options for the Playground when using SSL+subscriptions? I couldn't find any relevant ones in a search. Who's injecting that alias name into the Playground's error message? (even though my URL in playground did NOT use it...) Playground? aiohttp? Or graphql-ws??

Something else I just noticed: the Playground client error is showing a "ws:" scheme, as opposed to a "wss:" one. Perhaps that has to be configured in the Playground client? In the graphql-ws aiohttp example, "protocols" is set to "graphql-ws"; is "graphql-wss" also supported? (or _about to_ be supported??)

**Comment by bitmodeler** [comment]
OK, got it!
