### ISSUE TITLE
Error running Django with graphql-ws

### ISSUE THREAD

**Issue by furious-luke** [graphql-python/graphql-ws#68]
* GraphQL AioWS version: running off master branch
* Python version: 3.9.5
* Operating System: Arch Linux

### Description

I'm trying to run a basic Django server with subscriptions enabled and I'm receiving an error on the command line.

### What I Did

I prepared a basic Django server, enabled channels, and confirmed everything was working.

I then setup graphql-ws as described in the README. When I launch the server I see the following on the command line (it gets printed repeatedly):

```bash
Exception inside application: object.__init__() takes exactly one argument (the instance to initialize)
Traceback (most recent call last):
  File "/home/luke/.cache/pypoetry/virtualenvs/annai-EdSLGIjn-py3.9/lib/python3.9/site-packages/channels/staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "/home/luke/.cache/pypoetry/virtualenvs/annai-EdSLGIjn-py3.9/lib/python3.9/site-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "/home/luke/.cache/pypoetry/virtualenvs/annai-EdSLGIjn-py3.9/lib/python3.9/site-packages/channels/routing.py", line 150, in __call__
    return await application(
  File "/home/luke/.cache/pypoetry/virtualenvs/annai-EdSLGIjn-py3.9/lib/python3.9/site-packages/asgiref/compatibility.py", line 33, in new_application
    instance = application(scope)
  File "/home/luke/.cache/pypoetry/virtualenvs/annai-EdSLGIjn-py3.9/lib/python3.9/site-packages/channels/generic/websocket.py", line 159, in __init__
    super().__init__(*args, **kwargs)
TypeError: object.__init__() takes exactly one argument (the instance to initialize)
```

**Comment by fabienheureux** [comment]
Are you using the master branch or 0.3.1 ? 
Do you have some more information about the README you used to setup your project ?

**Comment by furious-luke** [comment]
Hey @fabienheureux! Please see the associated PR linked above for the fix I used.

**Comment by fabienheureux** [comment]
Fixed in https://github.com/graphql-python/graphql-ws/commit/94694e8b8d9aae52cf4da5eb7ef892285d58da17
